runtime: python313

entrypoint: uvicorn api.main:app --host 0.0.0.0 --port $PORT

instance_class: F1 # <-- MOVED: This should be a top-level property

handlers:
  - url: /static
    static_dir: static
    expiration: 30d 0h 0m 0s

  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

env_variables:
  ENV: "prod"
  GOOGLE_CLOUD_PROJECT: ai-voice-faq # Your GCP Project ID
